version: "3.7"

services:
  unit-test:
    container_name: small-logger-unit-test
    build: .
    environment:
      - BUILD=1 # If set to 0, the unit test are not launched and container will sleep to let you run all tests commands you want when you develop tests
    volumes:
      - .:/usr/lib/small-logger